production:
  solr:
    hostname: archive2
    port: 8983
    path: '/solr/default'
    min_memory: 1G
    max_memory: 1G
    log_level: WARNING

development:
  solr:
    hostname: localhost
    port: 8982
    path: /solr/development
    log_level: INFO

test:
  solr:
    hostname: localhost
    port: 8981
    log_level: WARNING
    path: /solr/test
    