production:
  solr:
    hostname: archive2
    port: 8080 #Tomcat default
    path: '/solr'
    log_level: WARNING

development:
  solr:
    hostname: localhost
    port: 8982
    solr_home: solr
    log_level: INFO

test:
  solr:
    hostname: localhost
    port: 8981
    log_level: WARNING
    
